esphome:
  name: esp8266
  friendly_name: esp8266

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "your Key"

ota:
  password: "your PW"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
  
uart:
  id: uart_a
  tx_pin: GPIO5
  rx_pin: GPIO4
  baud_rate: 19200
  data_bits: 8
  stop_bits: 1

modbus:
  send_wait_time: 10ms
  id: modbus_a

modbus_controller:
  - id: modbus_controller_a
    modbus_id: modbus_a
    address: 0x01
    update_interval: 3s
  - id: modbus_controller_b
    modbus_id: modbus_a
    address: 0x02
    update_interval: 3s


# Zähler OG

sensor:
  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "OG_l1_volts"
    name: "OG L1 Spannung"
    address: 0x0000
    value_type: FP32
    register_type: read
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "OG_l2_volts"
    name: "OG L2 Spannung"
    address: 0x0002
    value_type: FP32
    register_type: read
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "OG_3_volts"
    name: "OG L3 Spannung"
    address: 0x0004
    value_type: FP32
    register_type: read
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "OG_l1_power"
    name: "OG L1 Power"
    address: 0x000C
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "OG_l2_power"
    name: "OG L2 Power"
    address: 0x000E
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "OG_l3_power"
    name: "OG L3 Power"
    address: 0x0010
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "OG_sum_power"
    name: "OG Power"
    address: 0x0034
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_a
    id: "OG_import_energy"
    name: "OG Energy"
    address: 0x0048
    register_type: read
    value_type: FP32
    device_class: "energy"
    state_class: "total"
    unit_of_measurement: "kWh"
    skip_updates: 60
    accuracy_decimals: 2



# Zähler EG

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_b
    id: "EG_l1_volts"
    name: "EG L1 Spannung"
    address: 0x0000
    value_type: FP32
    register_type: read
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_b
    id: "EG_l2_volts"
    name: "EG L2 Spannung"
    address: 0x0002
    value_type: FP32
    register_type: read
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_b
    id: "EG_3_volts"
    name: "EG L3 Spannung"
    address: 0x0004
    value_type: FP32
    register_type: read
    device_class: "voltage"
    state_class: "measurement"
    unit_of_measurement: "V"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_b
    id: "EG_l1_power"
    name: "EG L1 Power"
    address: 0x000C
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_b
    id: "EG_l2_power"
    name: "EG L2 Power"
    address: 0x000E
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_b
    id: "EG_l3_power"
    name: "EG L3 Power"
    address: 0x0010
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"


  - platform: modbus_controller
    modbus_controller_id: modbus_controller_b
    id: "EG_sum_power"
    name: "EG Power"
    address: 0x0034
    value_type: FP32
    register_type: read
    device_class: "power"
    state_class: "measurement"
    unit_of_measurement: "W"

  - platform: modbus_controller
    modbus_controller_id: modbus_controller_b
    id: "EG_import_energy"
    name: "EG Energy"
    address: 0x0048
    register_type: read
    value_type: FP32
    device_class: "energy"
    state_class: "total"
    unit_of_measurement: "kWh"
    skip_updates: 60
    accuracy_decimals: 2

  


